// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArYjmy27RW3EII4wSl1QEygIkF_5UvLr0',
    appId: '1:907152902636:web:f8e375898a6f1449e398c9',
    messagingSenderId: '907152902636',
    projectId: 'movies-b88a0',
    authDomain: 'movies-b88a0.firebaseapp.com',
    storageBucket: 'movies-b88a0.appspot.com',
    measurementId: 'G-MXJK3ML6S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCufvotlhsrYVkIQrxBnt8aRnTRzgcWL8Q',
    appId: '1:907152902636:android:d9e4c9b9ed2acd2fe398c9',
    messagingSenderId: '907152902636',
    projectId: 'movies-b88a0',
    storageBucket: 'movies-b88a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTgH-XhvF9SxlHbvA6jKDeVjw7Aumsoqs',
    appId: '1:907152902636:ios:490d3521d32e1d88e398c9',
    messagingSenderId: '907152902636',
    projectId: 'movies-b88a0',
    storageBucket: 'movies-b88a0.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTgH-XhvF9SxlHbvA6jKDeVjw7Aumsoqs',
    appId: '1:907152902636:ios:490d3521d32e1d88e398c9',
    messagingSenderId: '907152902636',
    projectId: 'movies-b88a0',
    storageBucket: 'movies-b88a0.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArYjmy27RW3EII4wSl1QEygIkF_5UvLr0',
    appId: '1:907152902636:web:0d0d4c3851c48aefe398c9',
    messagingSenderId: '907152902636',
    projectId: 'movies-b88a0',
    authDomain: 'movies-b88a0.firebaseapp.com',
    storageBucket: 'movies-b88a0.appspot.com',
    measurementId: 'G-HRMHBQS2DQ',
  );
}
